### ISSUE TITLE
How do I download PC Software?

### ISSUE THREAD

**Issue by CHOJUNGHUN** [lujji/stm8-bootloader#2]
Hello lujji.

I am designing the STM8AF5288 boot loader with reference to your code.
Compillers are using IAR STM8. You can create S19, BIN, HEX File from IAR.
As a first question, what is the PC Software to validate your code?
Is it ST Flash Loder?
Currently I am building my bootloader code. The verification environment is the first priority. Thank you for your help.
Thank you.

I look forward to your reply.

**Comment by lujji** [comment]
Use this Python script to upload your code: https://github.com/lujji/stm8-bootloader/blob/master/uploader/boot.py
